[versions]
agp = "9.3.1"
kotlin = "2.4.20"
dav4jvm = "4.1.0"
ktor = "3.4.0"
desugar = "2.1.5"
ezvcard = "0.12.2"
ical4j = "4.3.0"
commonsCodec = "1.17.1"
commonsLang3 = "3.15.0"
androidxCore = "1.13.1"
appcompat = "1.7.0"
material = "1.12.0"
junit = "4.13.2"

[libraries]
dav4jvm = { module = "com.github.bitfireAT:dav4jvm", version.ref = "dav4jvm" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
desugar-jdk-libs-nio = { module = "com.android.tools:desugar_jdk_libs_nio", version.ref = "desugar" }
ezvcard = { module = "com.googlecode.ez-vcard:ez-vcard", version.ref = "ezvcard" }
ical4j = { module = "org.mnode.ical4j:ical4j", version.ref = "ical4j" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commonsCodec" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang3" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
